apiVersion: v1
name: test_jenkins
version: 0.0.1
description: Test with nginx
keywords:
  - Test
  - nginx
home: "https://github.com/PasLepera/test_repo"
maintainers:
  - name: "Pasquale"
    email: ""
tillerVersion: ">=2.8.0"
engine: gotpl
